### ISSUE TITLE
Display Meta Data for files (Date, size, Maybe imageSize or duration)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-client#176]
When files are listed, display the following information:

- [ ] date of modification
- [x] size (bytes, Kb, Mb, Gb)
- [ ] height/width of image
- [ ] duration of movie

[Trello](https://trello.com/c/m1pxAsdv/310-display-meta-data-for-files-date-size-maybe-imagesize-or-duration)
